### ISSUE TITLE
It is working?

### ISSUE THREAD

**Issue by JiLiZART** [MrKashlakov/enb-transform-flow#7]
При сборке вылетает на 

```
TypeError: Cannot read property 'get' of undefined
    at node_modules/enb-transform-flow/techs/transform-flow.js:84:21
```

Что привело меня к  строчке 

``` js
var sharedResources = this.node.getSharedResources();
var fileCache = sharedResources.fileCache; // << тут undefined
```

**Comment by MrKashlakov** [comment]
С версией ENB из upstream не работает, пока совместим с версией из этого PR: https://github.com/enb/enb/pull/449

**Comment by JiLiZART** [comment]
@MrKashlakov а с этой веткой тоже не работает, там `sharedResources.fileCache` так же пуст :(

**Comment by MrKashlakov** [comment]
Попробую отыскать нужную ветку.

**Comment by j0tunn** [comment]
там не ветку нужно искать, там API поменялся `fileCache` теперь не в `sharedResources`, а в `cache` (сюрприз-сюрприз). Смотри доку в PR

**Comment by MrKashlakov** [comment]
Да, спасибо! Думал там менее свежий  PR. Запилю поддержку актуального API
